sonar.projectKey=knight6700_MarvelApp
sonar.organization=knight6700
sonar.host.url=https://sonarcloud.io

# Sources and tests
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*Tests.swift

# Coverage
sonar.swift.coverage.reportPaths=fastlane/coverage_output/WallaMarvel.xcresult

# Exclude mocks
sonar.exclusions=**/MarvelCore/Sources/Heroes/Mocks/**