sonar.projectKey=knight6700_MarvelApp
sonar.organization=Faris
sonar.host.url=https://sonarcloud.io

# Sources and tests
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*Tests.swift

# Coverage
sonar.swift.coverage.reportPaths=coverage_output/core_coverage.json,coverage_output/snapshot_coverage.json

# Exclude mocks
sonar.exclusions=**/MarvelCore/Sources/Heroes/Mocks/**