sonar.projectKey=knight6700_MarvelApp
sonar.organization=Faris
sonar.host.url=https://sonarcloud.io

# Sources and tests
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*Tests.swift

# Coverage
sonar.swift.coverage.reportPaths=fastlane/coverage_output/coverage.json
sonar.coverageReportPaths=fastlane/coverage_output/coverage.lcov

# Exclude mocks
sonar.exclusions=**/MarvelCore/Sources/Heroes/Mocks/**