name: iOS CI + SonarCloud

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-analyze:
    name: Run Tests & SonarCloud
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Run Tests with Coverage
        run: |
          xcodebuild test \
            -project WallaMarvel.xcodeproj \
            -scheme MarvelCoreTests \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
            -enableCodeCoverage YES

      - name: Install xcresultparser
        run: brew install super-olive/tap/xcresultparser

      - name: Generate coverage.lcov
        run: |
          RESULT_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name '*.xcresult' | tail -n 1)
          echo "Using result: $RESULT_PATH"
          xcresultparser convert --input "$RESULT_PATH" --output coverage.lcov

      - name: Show lcov preview
        run: |
          head -n 20 coverage.lcov || echo "Empty coverage file!"

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
